Implement auto-cycle event quests
ZeruLight/Erupe pull request #81
Opened 2023-08-19 23:26 UTC by Malckyor

This is just a fancy and automatisation for auto-cycling weekly quests, in the original server there was something like this so instead of manually doing all of this work I offer the code to do that automatically. This also should be implemented for a few tabs from the Road Shop and Gacha.

## How does this work?
* Turn the "WeeklyQuestCycle" to true if you want the quests to cycle, set to false if you dislike the cycling option.
* Set the quests into the database like you should, there you'll see two new columns.
* Set a value between 1-5 (represents week of the month) in the "weekly_cycle" next to the quest ID you want to cycle and it should show in the desired cycle. The other "available_in_all_cycles" table is set to true by default, setting this to true will make the quest be available in all cycles (self explanatory). Setting multiples entries of the same quest in different cycles should make them available in their respective cycles if desired. 
**Note:** The amount of cycles can be changed in handlers_quest.go, search for newCycle := (currentCycle % 5) + 1 and change the 5 to the amount of cycles you want.
* The "weekly_cycle_info" table stores the current cycle and timestamp, you can just ignore this unless you want to manually set the current cycle and timestamp, this will be auto updated after hitting monday midnight (it should, my timezone in my pc is weird so I don't want to calculate).

That's it, all the quests within the database should cycle if set to do so, just don't forget about the client limit, for FW5 it loads around 83 quests and for ZZ it loads around 256 quests.
Tested and confirmed to be working with FW5 and ZZ, I recommend having different tables to have their event quests to avoid issues of non-existing content, I commented a leftover of my personal customization there, that code is recommended if you have multiple event quests tables.

2023-08-20 06:22 UTC, sekaiwish commented
> for FW5 it loads around 83 quests and for ZZ it loads around 512 quests
There is no such limit defined in the disassembly of the program, every version of MHF supports up to 256 enumerated download quests. If 256 quests are not able to load then an error has occurred.

2023-08-20 06:29 UTC, sekaiwish commented
This can definitely be rewritten in a way that does not require a new database table, and also should probably be rewritten in such a way that the Quest cycle can have any number of periods with any number of lengths, it would be a waste to have this only ever rotate something over a period of FIVE weeks. Additionally, Quests should have the option to appear in both multiple cycles AND all cycles.

2023-08-20 16:00 UTC, Malckyor commented
> There is no such limit defined in the disassembly of the program, every version of MHF supports up to 256 enumerated download quests. If 256 quests are not able to load then an error has occurred.

It's already tested and proved that the ZZ client can show 512, but I do remember you saying about the size of the files, that's why I also said "around those values", I don't know what and where you saw that, but somehow maybe differently but it can certainly load that many quests.
![image](https://github.com/ZeruLight/Erupe/assets/68492734/348a3725-4e15-401f-afe8-3443f941f0cb)

2023-08-20 18:29 UTC, Malckyor commented
> Additionally, Quests should have the option to appear in both multiple cycles AND all cycles.

Can you provide me more details about this? The way it is now it either appears if they are set to an specific cycle if they are not set to all cycles and if they are to appear in all cycles then whatever else is set is ignored.

The rest you suggested work reworked, though I'm not so sure if I should use the events table and setting a new event type since I don't know exactly how they work but I feel it shouldn't have any issues and it's somehow an event so... I'd prefer you change anything you think it's better.

2023-11-12 23:19 UTC, matthe815 requested changes

2023-11-12 23:19 UTC, matthe815 commented on server/channelserver/handlers_quest.go
> +	rows, err := s.server.db.Query("SELECT id, COALESCE(max_players, 4) AS max_players, quest_type, quest_id, COALESCE(mark, 0) AS mark, start_time, active_duration, inactive_duration FROM " + tableName
If you were to keep the tableName variable rather than hardcoding it, I think it'd be better to use string.Format here.

2023-11-12 23:19 UTC, matthe815 commented on server/channelserver/handlers_quest.go
> +			_, err := s.server.db.Exec("UPDATE "+tableName+" SET start_time = $1 WHERE quest_id = $2", rotationTime, questId)
Same here with this line. Although I think just hardcoding it would be better unless the G7 event quest format is that much different.

2023-11-12 23:19 UTC, matthe815 commented on server/channelserver/handlers_quest.go
> +	var tableName = "event_quests"
Is the data structure for event_quests between versions different enough to require entirely different tables?

2023-11-18 08:22 UTC, matthe815 commented
Most of the clean-up should be done, just need to wait a bit to test cycling.

2023-11-19 19:04 UTC, matthe815 approved these changes

2023-11-24 08:26 UTC, merged